### ISSUE TITLE
YouTube Provider

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vidstack#13]
## Tasks

- [ ] Implement YouTube Provider
- [ ] Installation Docs (https://www.vidstack.io/docs/player/getting-started/installation)
- [ ] Provider Docs (https://www.vidstack.io/docs/player/providers/youtube)

## References

- https://developers.google.com/youtube/iframe_api_reference
- https://github.com/vime-js/vime/tree/master/core/src/components/providers/youtube

**Comment by kimcorros** [comment]
Any update on this one?

**Comment by kimcorros** [comment]
Is there any update for this one?

**Comment by kimcorros** [comment]
Any update?

**Comment by josh-tt** [comment]
Also wondering about this and any eta on v1.0.

**Comment by mihar-22** [comment]
Working on it all as we speak :) Hoping to hit a good pace for releases soon and then I can give a better ETA. We'll announce date for 1.0 once we're confident on a date.

**Comment by tovutifunk** [comment]
Any updates or official traction to a release date on this item?

**Comment by GabrielGallagher** [comment]
Any news?

**Comment by adrian7** [comment]
Also looking for an update here. I'm currently using Vine.

**Comment by profd2004** [comment]
Exciting! Still panning for v1 launch this month?

**Comment by kimcorros** [comment]
Any update on this one? It's been a year.

**Comment by billygozutok** [comment]
👋 @kimcorros, we have a [player roadmap](https://github.com/orgs/vidstack/projects/1/views/1?groupedBy%5BcolumnId%5D=Milestone) that you can look through and follow along. At this point in time, we don't have Youtube allocated to a milestone. This means we don't know when or if we will go ahead with building a Youtube integration.

**Comment by Alfagun74** [comment]
Thanks for the damage control there @vidstack...

**Comment by hcavanaugh** [comment]
Curious on this status as well, as well as the timeline for 1.0. Using Plyr until youtube and vimeo providers are included in vidstack

**Comment by GabrielGallagher** [comment]
> Curious on this status as well, as well as the timeline for 1.0. Using Plyr until youtube and vimeo providers are included in vidstack

@hcavanaugh In their Discord, on 09/08/2023 they announced that there are "No plans for YouTube/Vimeo at the moment."

**Comment by mihar-22** [comment]
There's no plans at this time to support YouTube as we're focused on standard providers (audio/video/hls/dash). We may change our mind in the future, and will discuss it further with the community soon.

**Comment by GabrielGallagher** [comment]
Yeah it probably shouldn't be billed as a successor/replacement for Vime/Plyr if there's not only no way for people using those players to make their projects work with Vidstack, and no plan to achieve even vaguely similar capabilities. That's not a criticism of Vidstack which is great for what it is and understandably doesn't want to support the subpar limited capabilities of YouTube integration due to the ridiculous limitations Google places on that. It's just not the same kind of tool, and while nobody is entitled to a FOSS project meeting their needs, Vime/Plyr clearly meet a very different use case that Vidstack isn't even planning to be able to replicate so it feels a bit disingenuous to consider Vidstack a viable replacement/successor. There should at least be some warning before people waste too much time trying to adopt this like we did back when the YouTube stuff was supposed to be out imminently, ideally without requiring digging through GitHub issues or searching through Discord.

**Comment by mihar-22** [comment]
I'm going above and beyond with Vidstack to bring much more than Vime/Plyr initially provided. This might be one of the most feature packed players on the web in general right now. I understand people want YouTube/Vimeo but there's nothing we can reasonably provide on top of those disaster embeds. They end up in a net loss for everyone, the devs trying to build custom experiences with it (which it's not built for), and the users having to use it.

There's no reasonable middle ground here other than providing better tooling and making streaming more accessible through better tools/services/price. Ultimately, we're pushing for a win for everyone and there's nothing disingenuous about that. There's also no reason we should bear the burden of maintaining embeds for companies who give nothing back and only make it harder to integrate with. It's stupid and a waste of time.

I took a while to decide because I went back and forth on what the right thing to do is and weighed it out for ages. As mentioned, I think the right thing to do is not include it. I think Vime/Plyr support them reasonably well. If anyone would like to take the burden on they can fork Vime, Plyr, or Vidstack and go for it.

**Comment by GabrielGallagher** [comment]
I agree with you, I just wish it was clear from the project readme or something that this use case is ruled out as it is a commonly expected feature, especially if you're coming from Vime/Plyr and being told this is the successor to those. As it stands now you have to do a fair bit of digging to find out.

**Comment by mihar-22** [comment]
My intention already was to update Vime/Plyr repos pinned isues and write up a new discussion with all of this information. What to expect with migrating over and so on. I have a bunch of prep tasks fixing things and helping people, so it should be done this week or next. Hence why I kind of left it open by saying, "we may change our mind in the future, and will discuss it further with the community soon."

**Comment by wplit** [comment]
@mihar-22 

If needing Youtube/Vimeo, is your recommendation to still use Vime then? I had thought from previous announcements that Vidstack was intended as being the new replacement and Vime wouldn't be continued. (admittedly I wasn't following things so closely so am unsure of the details) I also see the same written on the Plyr github page.

**Comment by mihar-22** [comment]
If you want Vime/YouTube then you can either use the direct embeds (recommended) or use Vime/Plyr. There isn't anything reasonable we can build on the embeds. We're ultimately pushing for a better experience for everyone and making streaming more accessible. I still see Vidstack as a perfect replacement with enhanced set of features. The embeds do not make or break that because we can't provide anyhting really over them that you can't get from direct embed or Vime/Plyr today.

**Comment by mihar-22** [comment]
We've changed our mind. To not leave anyone behind we'll be adding YouTube: https://github.com/vidstack/vidstack/issues/944
