### ISSUE TITLE
Vimeo Provider

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vidstack#14]
## Tasks

- [ ] Implement Vimeo Provider
- [ ] Installation Docs (https://www.vidstack.io/docs/player/getting-started/installation)
- [ ] Provider Docs (https://www.vidstack.io/docs/player/providers/vimeo)

## References

- https://developer.vimeo.com/player/sdk
- https://github.com/vime-js/vime/tree/master/core/src/components/providers/vimeo

**Comment by tamizhvendan** [comment]
Hi @mihar-22,

Thanks for working on this. Any updates on it's progress?

**Comment by mihar-22** [comment]
Not yet @tamizhvendan, trying to figure out some foundation tooling issues right now. Work on providers will resume once we get back on track with the 1.0 board.

**Comment by tamizhvendan** [comment]
Thanks a ton for the awesome work @mihar-22! Looking forward

**Comment by ousszizou** [comment]
thanks for the goood work <3
Any updates on it's progress?

**Comment by billygozutok** [comment]
👋 @ousszizou, thank you heaps! In regard to this issue and updates on progress, you can track and follow our [player roadmap](https://github.com/orgs/vidstack/projects/1/views/1?groupedBy%5BcolumnId%5D=Milestone). You will find all our tasks and plans fleshed out there ☺️ Keep in mind that this roadmap can adjust and change 👍

**Comment by mifo111** [comment]
thanks for the awesome work.
Question regarding the Vimeo Provider. You have removed the milestone for this provider. What does this mean exactly?

Br,
Michael

**Comment by mihar-22** [comment]
There's no plans at this time to support Vimeo as we're focused on standard providers (audio/video/hls/dash). We may change our mind in the future, and will discuss it further with the community soon.

**Comment by mihar-22** [comment]
We've changed our mind. To not leave anyone behind we'll be adding Vimeo: https://github.com/vidstack/vidstack/issues/945
