### ISSUE TITLE
Dailymotion Provider

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vidstack#15]
## Tasks

- [ ] Implement Dailymotion Provider
- [ ] Installation Docs (https://www.vidstack.io/docs/player/getting-started/installation)
- [ ] Provider Docs (https://www.vidstack.io/docs/player/providers/dailymotion)

## References

- https://developer.dailymotion.com/player
- https://github.com/vidstack/player/blob/main/docs/architecture/architecture.md#providers
- https://github.com/vime-js/vime/tree/master/core/src/components/providers/dailymotion

**Comment by mihar-22** [comment]
There's no plans anymore to support Dailymotion as we're focused on standard providers (audio/video/hls/dash).

**Comment by ByMykel** [comment]
Do you have any plans to implement Dailymotion? I guess it might be even more annoying than YouTube or Vimeo

![image](https://github.com/vidstack/player/assets/38622893/f5106193-251d-4034-a1ec-4ed3ea65f3e1)
