### ISSUE TITLE
Plyr Skin

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vidstack#74]
## Tasks

- [ ] Implement beautiful Plyr skin :)
- [ ] Installation Docs (https://www.vidstack.io/docs/player/getting-started/installation)
- [ ] Skins Docs (https://www.vidstack.io/docs/player/styling/skins)

## References

- https://plyr.io
- https://github.com/sampotts/plyr
- https://github.com/vime-js/vime/tree/master/core/src/components/ui/default-ui
- https://github.com/vime-js/vime/tree/master/core/src/components/ui/settings/default-settings
- https://github.com/vime-js/vime/tree/master/core/src/components/ui/controls/default-controls

**Comment by ottman** [comment]
Is there any chance we can escalate this?

**Comment by vbasky** [comment]
Hi Team,
       
             Is there a roadmap for when the support for the beautiful plyr skin will be added?

**Comment by mihar-22** [comment]
This issue is outdated now since our [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). We've moved from "skins" to "layouts" and will include Plyr fairly soon. It will definitely be available as part of the official 1.0 release.
