### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vidstack#79]
## Tasks

- [ ] Setup Cypress.
- [ ] Create simple HTML example in `examples` directory.
- [ ] **Optional.** Create simple Svelte example using SvelteKit in `examples` directory.
- [ ] **Optional.** Create simple Vue 3 example using Vite in `examples` directory.
- [ ] On each example test installing the package `@vidstack/player`, importing components and asserting they're rendered. Preferable to test using `<vds-default-skin>`.

## References

- https://github.com/vidstack/player/blob/main/docs/architecture/overview.md#testing
- https://github.com/vidstack/player/blob/main/docs/architecture/overview.md#examples

**Comment by mihar-22** [comment]
Closing for now, revisit later.
